# Site settings
title:          Digital Cinema-Writing / Will Luers
description:    "computational cinema, digital language arts, electronic literature"
baseurl:        
url:            "https://wluers.github.io"

# Author
author:
  name:         Will Luers
  url:          https://will-luers.com
  email:        wluers@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
